// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkdpx6cmbCJe93jb15hTcFnTVYK2yv-tY',
    appId: '1:1019168864120:android:acec43b1825f52f2cbfa8d',
    messagingSenderId: '1019168864120',
    projectId: 'restaurant-menu-333',
    storageBucket: 'restaurant-menu-333.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKv9N1Koh45xltBgzuaqqx_n8Y5Yglh3U',
    appId: '1:1019168864120:ios:665a2365b4a8866dcbfa8d',
    messagingSenderId: '1019168864120',
    projectId: 'restaurant-menu-333',
    storageBucket: 'restaurant-menu-333.appspot.com',
    iosClientId: '1019168864120-7evn7m3airq9k01cglentgutai7st2l9.apps.googleusercontent.com',
    iosBundleId: 'com.michalgudalewicz.restaurant',
  );
}
